### ISSUE TITLE
Some puzzle about avoidance between robots

### ISSUE THREAD

**Issue by yufengsjtu** [hikashi/TM-RRT_exploration#4]
Hi,excuse me for a moment.I wonder how this algorithm ensure avoidance bewteen robots,i mean how to ensure that path planning does not collide each other after assigning target points?. Do i  need to put this robots away from each other?

**Comment by hikashi** [comment]
Hi,

This algorithm only concerns the allocation of waypoints based on the current position of the robots rather than doing the path planning. Path planning is done via movebase and collision avoidance is handled via movebase. 
As for the placement of the robot, the use case scenario would be all robots starting from the identical location as it requires map merging between sub-maps to allocate waypoints.

Hope that answers your question. Thanks.

Regards,
Billy
